// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminHistoryLink: typeof import('./../src/components/admin/historyLink.vue')['default']
    AdminMenu: typeof import('./../src/components/admin/menu.vue')['default']
    AdminNavbar: typeof import('./../src/components/admin/navbar.vue')['default']
    Breadcrumb: typeof import('./../src/components/breadcrumb.vue')['default']
    Dialog: typeof import('./../src/components/dialog.vue')['default']
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default']
    MemberAdduser: typeof import('./../src/components/member/adduser.vue')['default']
    MemberEditorAvatar: typeof import('./../src/components/member/editorAvatar.vue')['default']
    Notification: typeof import('./../src/components/notification.vue')['default']
    Pagination: typeof import('./../src/components/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSetting: typeof import('./../src/components/ThemeSetting.vue')['default']
    WangEditorEditor: typeof import('./../src/components/wangEditor/editor.vue')['default']
  }
}

export {}
